"""create new chat messag tables

Revision ID: 2d60ec1df999
Revises: 459f8b733bcc
Create Date: 2025-10-09 12:00:52.008668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d60ec1df999'
down_revision = '459f8b733bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
