"""create tables

Revision ID: 53dde36851de
Revises: 
Create Date: 2025-10-19 11:29:04.959615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dde36851de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_address'), 'suppliers', ['address'], unique=False)
    op.create_index(op.f('ix_suppliers_contact_person'), 'suppliers', ['contact_person'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_phone_number'), 'suppliers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_name'), 'suppliers', ['supplier_name'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('pharmacy_inventory',
    sa.Column('drug_id', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    op.create_index(op.f('ix_pharmacy_inventory_brand'), 'pharmacy_inventory', ['brand'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_category'), 'pharmacy_inventory', ['category'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_drug_id'), 'pharmacy_inventory', ['drug_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_drug_name'), 'pharmacy_inventory', ['drug_name'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_location'), 'pharmacy_inventory', ['location'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_supplier_id'), 'pharmacy_inventory', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_inventory_supplier_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_location'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_drug_name'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_drug_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_category'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_brand'), table_name='pharmacy_inventory')
    op.drop_table('pharmacy_inventory')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_suppliers_supplier_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_phone_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_contact_person'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_address'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
