"""Create DB Tables

Revision ID: 66dbd3c9a299
Revises: 
Create Date: 2025-10-25 00:23:52.656244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66dbd3c9a299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('doctor_name', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hospital', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctors_phone'), 'doctors', ['phone'], unique=True)
    op.create_table('employees',
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('emp_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_emp_id'), 'employees', ['emp_id'], unique=False)
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('pharmacy_inventory',
    sa.Column('drug_id', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('drug_id')
    )
    op.create_index(op.f('ix_pharmacy_inventory_brand'), 'pharmacy_inventory', ['brand'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_category'), 'pharmacy_inventory', ['category'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_drug_id'), 'pharmacy_inventory', ['drug_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_drug_name'), 'pharmacy_inventory', ['drug_name'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_location'), 'pharmacy_inventory', ['location'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_supplier_id'), 'pharmacy_inventory', ['supplier_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.Column('diagnosis', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_index(op.f('ix_prescriptions_customer_id'), 'prescriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_id'), 'prescriptions', ['prescription_id'], unique=False)
    op.create_table('purchases',
    sa.Column('purchase_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=10), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_purchases_purchase_id'), 'purchases', ['purchase_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('total_sale', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_emp_id'), 'sales', ['emp_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.create_table('purchase_details',
    sa.Column('purchase_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.String(length=50), nullable=False),
    sa.Column('drug_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['pharmacy_inventory.drug_id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.purchase_id'], ),
    sa.PrimaryKeyConstraint('purchase_detail_id')
    )
    op.create_index(op.f('ix_purchase_details_drug_id'), 'purchase_details', ['drug_id'], unique=False)
    op.create_index(op.f('ix_purchase_details_purchase_id'), 'purchase_details', ['purchase_id'], unique=False)
    op.create_table('sales_details',
    sa.Column('sale_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.String(length=50), nullable=False),
    sa.Column('drug_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['pharmacy_inventory.drug_id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ),
    sa.PrimaryKeyConstraint('sale_detail_id')
    )
    op.create_index(op.f('ix_sales_details_drug_id'), 'sales_details', ['drug_id'], unique=False)
    op.create_index(op.f('ix_sales_details_sale_id'), 'sales_details', ['sale_id'], unique=False)
    op.drop_table('pharmacy_inventorychat_messages')
    op.alter_column('suppliers', 'supplier_id',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('suppliers', 'supplier_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('suppliers', 'contact_person',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('suppliers', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('suppliers', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('suppliers', 'address',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_suppliers_address'), 'suppliers', ['address'], unique=False)
    op.create_index(op.f('ix_suppliers_contact_person'), 'suppliers', ['contact_person'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_phone_number'), 'suppliers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_name'), 'suppliers', ['supplier_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_supplier_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_phone_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_contact_person'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_address'), table_name='suppliers')
    op.alter_column('suppliers', 'address',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('suppliers', 'email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'phone_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('suppliers', 'contact_person',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'supplier_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'supplier_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.create_table('pharmacy_inventorychat_messages',
    sa.Column('drug_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('drug_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('brand', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('unit_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantity_in_stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('supplier_id', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('reorder_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('pharmacy_inventorychat_messages_ibfk_1')),
    sa.PrimaryKeyConstraint('drug_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_sales_details_sale_id'), table_name='sales_details')
    op.drop_index(op.f('ix_sales_details_drug_id'), table_name='sales_details')
    op.drop_table('sales_details')
    op.drop_index(op.f('ix_purchase_details_purchase_id'), table_name='purchase_details')
    op.drop_index(op.f('ix_purchase_details_drug_id'), table_name='purchase_details')
    op.drop_table('purchase_details')
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_emp_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_purchase_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_prescriptions_prescription_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_customer_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_pharmacy_inventory_supplier_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_location'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_drug_name'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_drug_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_category'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_brand'), table_name='pharmacy_inventory')
    op.drop_table('pharmacy_inventory')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_doctors_phone'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
