"""Create HumanReviews Table

Revision ID: 8fc19e236b4c
Revises: 66dbd3c9a299
Create Date: 2025-10-25 12:17:59.785380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc19e236b4c'
down_revision = '66dbd3c9a299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_id'), 'human_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_reviews_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    # ### end Alembic commands ###
