"""create new chat messag tables2

Revision ID: cd7be75f0aa7
Revises: 2d60ec1df999
Create Date: 2025-10-09 12:05:23.575839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7be75f0aa7'
down_revision = '2d60ec1df999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
